# Generated by Django 2.2.5 on 2019-11-27 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('location', models.CharField(default='', max_length=255, verbose_name='Локация')),
                ('gender', models.CharField(choices=[('NOT_SET', 'Не установлена'), ('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], default='NOT_SET', max_length=255, verbose_name='Пол')),
                ('nationality', models.CharField(default='', max_length=255, verbose_name='Национальность')),
                ('favourite_position', models.CharField(choices=[('NOT_SET', 'Не установлена'), ('GOALIE', 'Вратарь'), ('DEFENDER', 'Защитник'), ('MIDFIELDER', 'Полузащитник'), ('FORWARD', 'Нападающий')], default='NOT_SET', max_length=255, verbose_name='Любимая позиция')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('phone', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер телефона')),
                ('phone_activation_code', models.IntegerField(blank=True, default=None, null=True, verbose_name='Последний код активации номера телефона')),
                ('is_active_phone', models.BooleanField(default=False, verbose_name='Номер телефона подтвержден')),
                ('reliability', models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, verbose_name='Надежность')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/profile_images', verbose_name='Фото профиля')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на пользователя',
                'verbose_name_plural': 'Подписки на пользователей',
            },
        ),
    ]
