# Generated by Django 2.2.5 on 2019-11-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Токен')),
            ],
            options={
                'verbose_name': 'Токен авторизации',
                'verbose_name_plural': 'Токены авторизации',
            },
        ),
    ]
