# Generated by Django 2.2.5 on 2020-01-27 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=900, verbose_name='Описание')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('cover_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/game_covers', verbose_name='Обложка')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='images/game_photos', verbose_name='Фото игры')),
                ('timespan', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (в минутах)')),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Онлайн оплата')], default='ONLINE', max_length=255, verbose_name='Способ оплаты')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли')], default='RUB', max_length=255, verbose_name='Валюта')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=255, verbose_name='Уровень игры')),
                ('refund_money_if_game_is_cancelled', models.BooleanField(default=False, verbose_name='Возврат денег в случае отмены')),
                ('refundable_days', models.IntegerField(default=0, verbose_name='Возврат денег в случае отмены и предоставления уведомления за n дней')),
                ('min_players_count', models.PositiveIntegerField(verbose_name='Минимальное количество игроков в команде')),
                ('max_players_count', models.PositiveIntegerField(verbose_name='Максимальное количество игроков в команде')),
                ('players_count', models.PositiveIntegerField(default=0, verbose_name='Количество игроков')),
                ('registration_available', models.BooleanField(default=True, verbose_name='Открыта для регистрации')),
                ('cancel', models.BooleanField(default=False, verbose_name='Отменить')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.Quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['timespan'],
            },
        ),
        migrations.CreateModel(
            name='GamePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Скидка')),
                ('discount_units', models.CharField(max_length=10, verbose_name='Удиницы измирения')),
                ('summa_with_discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма со скидкой')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('places_count', models.IntegerField(verbose_name='Количество оплаченных мест')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WAITING_FOR_CAPTURE', 'Waiting for capture'), ('SUCCEEDED', 'Succeeded'), ('CANCELED', 'Canceled')], default='PENDING', max_length=255, verbose_name='Статус')),
                ('cancel_message', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина отмены')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.Coupon', verbose_name='Купон')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж пользователя',
                'verbose_name_plural': 'Платежи пользователей',
            },
        ),
        migrations.CreateModel(
            name='GamePlayerEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень игры')),
                ('enjoyed_playing', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Понравилось играть')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game', verbose_name='Игра')),
                ('ranked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_user', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемый')),
            ],
            options={
                'verbose_name': 'Оценка участника',
                'verbose_name_plural': 'Оценки участников',
            },
        ),
        migrations.CreateModel(
            name='GamePaymentRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, verbose_name='Идентификатор')),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Succeeded'), ('CANCELED', 'Canceled')], max_length=10, verbose_name='Статус')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('currency', models.CharField(max_length=10, verbose_name='Валюта')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game', verbose_name='Игра')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.GamePayment', verbose_name='Платеж')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Возврат платежа пользователя',
                'verbose_name_plural': 'Возвраты платежей пользователей',
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('text', models.CharField(max_length=900, verbose_name='Комментарий')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к игре',
                'verbose_name_plural': 'Комментарии к игре',
                'ordering': ['-timestamp'],
            },
        ),
    ]
