# Generated by Django 2.2.5 on 2019-12-24 15:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(blank=True, default='', max_length=900, verbose_name='Описание')),
                ('genre', models.CharField(max_length=255, verbose_name='Жанр')),
                ('cover_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/game_covers', verbose_name='Обложка')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='images/game_photos', verbose_name='Фото игры')),
                ('timespan', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (в минутах)')),
                ('payment_method', models.CharField(choices=[('ONLINE', 'Онлайн оплата')], default='ONLINE', max_length=255, verbose_name='Способ оплаты')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли')], default='RUB', max_length=255, verbose_name='Валюта')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=255, verbose_name='Уровень игры')),
                ('refund_money_if_game_is_cancelled', models.BooleanField(default=False, verbose_name='Возврат денег в случае отмены')),
                ('refundable_days', models.IntegerField(default=0, verbose_name='Возврат денег в случае отмены и предоставления уведомления за n дней')),
                ('min_players_count', models.PositiveIntegerField(verbose_name='Минимальное количество игроков в команде')),
                ('max_players_count', models.PositiveIntegerField(verbose_name='Максимальное количество игроков в команде')),
                ('players_count', models.PositiveIntegerField(default=0, verbose_name='Количество игроков')),
                ('registration_available', models.BooleanField(default=True, verbose_name='Открыта для регистрации')),
                ('cancel', models.BooleanField(default=False, verbose_name='Отменить')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.Quest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['timespan'],
            },
        ),
        migrations.CreateModel(
            name='GamePlayerEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень игры')),
                ('enjoyed_playing', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Понравилось играть')),
                ('appraiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оценщик')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game', verbose_name='Игра')),
                ('ranked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_user', to=settings.AUTH_USER_MODEL, verbose_name='Оцениваемый')),
            ],
            options={
                'verbose_name': 'Оценка участника',
                'verbose_name_plural': 'Оценки участников',
            },
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('text', models.CharField(max_length=900, verbose_name='Комментарий')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий к игре',
                'verbose_name_plural': 'Комментарии к игре',
                'ordering': ['-timestamp'],
            },
        ),
    ]
