# Generated by Django 2.2.5 on 2020-01-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepayment',
            name='cancel_message',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Причина отмены'),
        ),
    ]
