version: '3'

services:
  web:
    container_name: koroka_games
    build: .
    command: gunicorn -b 0.0.0.0:8000 korobka_games.wsgi:application
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/korobka_games
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgres:
    container_name: postgres
    image: postgres:12.1-alpine
    restart: always
    env_file:
      - .env