# Generated by Django 2.2.5 on 2020-01-22 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Код')),
                ('start_date', models.DateField(verbose_name='Начало действия')),
                ('end_date', models.DateField(verbose_name='Окончание действия')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Скидка')),
                ('units', models.CharField(choices=[('PERCENT', '%'), ('RUB', 'RUB')], max_length=7, verbose_name='Единицы измерения')),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Индивидуальный'), ('GENERAL', 'Общий')], max_length=15, verbose_name='Тип')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
            },
        ),
    ]
