# Generated by Django 2.2.5 on 2019-12-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecomment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Комментарий к игре', 'verbose_name_plural': 'Комментарии к игре'},
        ),
        migrations.AlterField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=255, verbose_name='Уровень игры'),
        ),
    ]
