# Generated by Django 2.2.5 on 2019-12-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservedplaceinteam',
            name='reserved_position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='players_count_per_team',
        ),
        migrations.RemoveField(
            model_name='userinteam',
            name='user_position',
        ),
    ]
