# Generated by Django 2.2.5 on 2020-02-09 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAME_MESSAGE', 'Сообщение связанное с игрой'), ('SIMPLE_MESSAGE', 'Простое сообщение')], max_length=255, verbose_name='Тип')),
                ('timespan', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('message', models.CharField(max_length=255, verbose_name='Сообщение')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/timeline_images', verbose_name='Фото')),
                ('creator', models.CharField(choices=[('ADMIN', 'Admin'), ('APP', 'App')], default='ADMIN', max_length=255, verbose_name='Создатель')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Game', verbose_name='Игра')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Элемент ленты',
                'verbose_name_plural': 'Элементы ленты',
            },
        ),
    ]
