version: '3'

volumes:
  postgres_data: {}
  storage_data: {}

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: ../.env.json
  redis:
    image: redis
    ports:
      - '6379:6379'
  django:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - storage_data:/src/media
    depends_on:
      - postgres
      - redis
    env_file: ../.env.json
    ports:
      - "8080:8000"
      - "8081:443"
    links:
      - postgres
      - redis
