# Generated by Django 2.2.5 on 2019-12-03 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('location', models.CharField(max_length=255, verbose_name='Локация (адрес)')),
                ('x_coordinate', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='Х координата')),
                ('y_coordinate', models.DecimalField(decimal_places=5, max_digits=7, verbose_name='У координата')),
                ('cover_image', models.ImageField(blank=True, default=None, null=True, upload_to='images/venue_covers', verbose_name='Обложка')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='images/venue_photos', verbose_name='Фото площадки')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Площадка',
                'verbose_name_plural': 'Площадки',
            },
        ),
        migrations.CreateModel(
            name='VenueSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.Venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Подписка на площадку',
                'verbose_name_plural': 'Подписки на площадки',
            },
        ),
        migrations.CreateModel(
            name='VenueComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('text', models.CharField(max_length=900, verbose_name='Комментарий')),
                ('scores', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, verbose_name='Оценка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='venues.Venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Комментарий площадки',
                'verbose_name_plural': 'Комментарии площадки',
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('color', models.CharField(max_length=7, verbose_name='Цвет ветки (в формате #FFFFFF)')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro_stations', to='venues.Venue', verbose_name='Площадка')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
            },
        ),
    ]
