# Generated by Django 2.2.5 on 2019-12-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuecomment',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Комментарий площадки', 'verbose_name_plural': 'Комментарии площадки'},
        ),
    ]
